# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_main = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_main.setContentsMargins(20, 20, 40, 20)
        self.horizontalLayout_main.setSpacing(30)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setMinimumSize(QtCore.QSize(600, 0))
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap(":/newPrefix/anh_thu_vien.bmp"))
        self.label_image.setScaledContents(True)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.horizontalLayout_main.addWidget(self.label_image)
        self.verticalLayout_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_right.addItem(spacerItem)
        self.horizontalLayout_form_center_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_form_center_2.setObjectName("horizontalLayout_form_center_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_form_center_2.addItem(spacerItem1)
        self.verticalLayout_form = QtWidgets.QVBoxLayout()
        self.verticalLayout_form.setSpacing(15)
        self.verticalLayout_form.setObjectName("verticalLayout_form")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: black;")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_form.addWidget(self.label_title)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_form.addItem(spacerItem2)
        self.label_user = QtWidgets.QLabel(self.centralwidget)
        self.label_user.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_user.setFont(font)
        self.label_user.setStyleSheet("color: black;")
        self.label_user.setObjectName("label_user")
        self.verticalLayout_form.addWidget(self.label_user)
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username.setMaximumSize(QtCore.QSize(400, 40))
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout_form.addWidget(self.lineEdit_username)
        self.label_pass = QtWidgets.QLabel(self.centralwidget)
        self.label_pass.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_pass.setFont(font)
        self.label_pass.setStyleSheet("color: black;")
        self.label_pass.setObjectName("label_pass")
        self.verticalLayout_form.addWidget(self.label_pass)
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setMaximumSize(QtCore.QSize(400, 40))
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_form.addWidget(self.lineEdit_password)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_form.addItem(spacerItem3)
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setMaximumSize(QtCore.QSize(400, 50))
        self.btn_login.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("QPushButton {\n"
"    background-color: black;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #333333;\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout_form.addWidget(self.btn_login)
        self.horizontalLayout_form_center_2.addLayout(self.verticalLayout_form)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_form_center_2.addItem(spacerItem4)
        self.verticalLayout_right.addLayout(self.horizontalLayout_form_center_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_right.addItem(spacerItem5)
        self.horizontalLayout_main.addLayout(self.verticalLayout_right)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Đăng nhập - Hệ thống thư viện"))
        self.label_title.setText(_translate("mainWindow", "Đăng nhập"))
        self.label_user.setText(_translate("mainWindow", "Tên đăng nhập:"))
        self.lineEdit_username.setPlaceholderText(_translate("mainWindow", "Nhập tên tài khoản..."))
        self.label_pass.setText(_translate("mainWindow", "Mật khẩu:"))
        self.lineEdit_password.setPlaceholderText(_translate("mainWindow", "Nhập mật khẩu..."))
        self.btn_login.setText(_translate("mainWindow", "Đăng nhập"))
import anhthuvien_rc
