from PyQt5.QtWidgets import QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets

from .ui_main_window import Ui_MainWindow


class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_main = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_main.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_main.setSpacing(0)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.nav_panel = QtWidgets.QWidget(self.centralwidget)
        self.nav_panel.setMinimumSize(QtCore.QSize(200, 0))
        self.nav_panel.setObjectName("nav_panel")
        self.verticalLayout_nav = QtWidgets.QVBoxLayout(self.nav_panel)
        self.verticalLayout_nav.setContentsMargins(16, 24, 16, 24)
        self.verticalLayout_nav.setSpacing(8)
        self.verticalLayout_nav.setObjectName("verticalLayout_nav")
        self.label_app_title = QtWidgets.QLabel(self.nav_panel)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_app_title.setFont(font)
        self.label_app_title.setStyleSheet("color: #e8eaed;")
        self.label_app_title.setObjectName("label_app_title")
        self.verticalLayout_nav.addWidget(self.label_app_title)
        self.label_app_sub = QtWidgets.QLabel(self.nav_panel)
        self.label_app_sub.setStyleSheet("color: #9aa0a6; font-size: 12px;")
        self.label_app_sub.setObjectName("label_app_sub")
        self.verticalLayout_nav.addWidget(self.label_app_sub)
        spacerItem = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_nav.addItem(spacerItem)
        self.btn_nav_stats = QtWidgets.QPushButton(self.nav_panel)
        self.btn_nav_stats.setObjectName("btn_nav_stats")
        self.verticalLayout_nav.addWidget(self.btn_nav_stats)
        self.btn_nav_books = QtWidgets.QPushButton(self.nav_panel)
        self.btn_nav_books.setObjectName("btn_nav_books")
        self.verticalLayout_nav.addWidget(self.btn_nav_books)
        self.btn_nav_categories = QtWidgets.QPushButton(self.nav_panel)
        self.btn_nav_categories.setObjectName("btn_nav_categories")
        self.verticalLayout_nav.addWidget(self.btn_nav_categories)
        self.btn_nav_authors = QtWidgets.QPushButton(self.nav_panel)
        self.btn_nav_authors.setObjectName("btn_nav_authors")
        self.verticalLayout_nav.addWidget(self.btn_nav_authors)
        self.btn_nav_publishers = QtWidgets.QPushButton(self.nav_panel)
        self.btn_nav_publishers.setObjectName("btn_nav_publishers")
        self.verticalLayout_nav.addWidget(self.btn_nav_publishers)
        self.btn_nav_accounts = QtWidgets.QPushButton(self.nav_panel)
        self.btn_nav_accounts.setObjectName("btn_nav_accounts")
        self.verticalLayout_nav.addWidget(self.btn_nav_accounts)
        self.btn_nav_loans = QtWidgets.QPushButton(self.nav_panel)
        self.btn_nav_loans.setObjectName("btn_nav_loans")
        self.verticalLayout_nav.addWidget(self.btn_nav_loans)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_nav.addItem(spacerItem1)
        self.horizontalLayout_main.addWidget(self.nav_panel)
        self.stacked_screens = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_screens.setObjectName("stacked_screens")
        self.horizontalLayout_main.addWidget(self.stacked_screens)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stacked_screens.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thư viện"))
        self.label_app_title.setText(_translate("MainWindow", "Thư viện"))
        self.label_app_sub.setText(_translate("MainWindow", "Quản lý sách"))
        self.btn_nav_stats.setText(_translate("MainWindow", "Thống kê"))
        self.btn_nav_books.setText(_translate("MainWindow", "Sách"))
        self.btn_nav_categories.setText(_translate("MainWindow", "Thể loại"))
        self.btn_nav_authors.setText(_translate("MainWindow", "Tác giả"))
        self.btn_nav_publishers.setText(_translate("MainWindow", "Nhà xuất bản"))
        self.btn_nav_accounts.setText(_translate("MainWindow", "Tài Khoản"))
        self.btn_nav_loans.setText(_translate("MainWindow", "Mượn/Trả"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
